'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_snippetlist() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_snippetlist"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_snippetlist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_autocomplete_enabled() As Boolean
            Get
                Return CType(Me("set_autocomplete_enabled"),Boolean)
            End Get
            Set
                Me("set_autocomplete_enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_tasklisttodo() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_tasklisttodo"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_tasklisttodo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_tasklistcomplete() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_tasklistcomplete"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_tasklistcomplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DEFAULT")>  _
        Public Property set_defaultprojlocation() As String
            Get
                Return CType(Me("set_defaultprojlocation"),String)
            End Get
            Set
                Me("set_defaultprojlocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property temp_projlocation() As String
            Get
                Return CType(Me("temp_projlocation"),String)
            End Get
            Set
                Me("temp_projlocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_recentprojects() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_recentprojects"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_recentprojects") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\Java\jdk1.7.0_71\bin")>  _
        Public Property set_javaclasspath() As String
            Get
                Return CType(Me("set_javaclasspath"),String)
            End Get
            Set
                Me("set_javaclasspath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.google.com")>  _
        Public Property set_browserhome() As String
            Get
                Return CType(Me("set_browserhome"),String)
            End Get
            Set
                Me("set_browserhome") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>1</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>2</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>3</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>4</strin"& _ 
            "g>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>5</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>6</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>7</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>"& _ 
            "8</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>9</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>10</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>11</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "  <string>12</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>13</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>14</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>1"& _ 
            "5</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>16</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>17</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>18</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property set_quickpaste() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_quickpaste"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_quickpaste") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DEFAULT")>  _
        Public Property set_defaultdownloadlocation() As String
            Get
                Return CType(Me("set_defaultdownloadlocation"),String)
            End Get
            Set
                Me("set_defaultdownloadlocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200")>  _
        Public Property set_infopanelsize() As Integer
            Get
                Return CType(Me("set_infopanelsize"),Integer)
            End Get
            Set
                Me("set_infopanelsize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Default")>  _
        Public Property set_theme() As Global.MetroFramework.MetroThemeStyle
            Get
                Return CType(Me("set_theme"),Global.MetroFramework.MetroThemeStyle)
            End Get
            Set
                Me("set_theme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Consolas, 10pt")>  _
        Public Property set_defaultfont() As Global.System.Drawing.Font
            Get
                Return CType(Me("set_defaultfont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("set_defaultfont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_showinfopanelbydefault() As Boolean
            Get
                Return CType(Me("set_showinfopanelbydefault"),Boolean)
            End Get
            Set
                Me("set_showinfopanelbydefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_righttoleft() As Boolean
            Get
                Return CType(Me("set_righttoleft"),Boolean)
            End Get
            Set
                Me("set_righttoleft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CrLf")>  _
        Public Property set_endofline() As Global.ScintillaNET.Eol
            Get
                Return CType(Me("set_endofline"),Global.ScintillaNET.Eol)
            End Get
            Set
                Me("set_endofline") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_eolvisible() As Boolean
            Get
                Return CType(Me("set_eolvisible"),Boolean)
            End Get
            Set
                Me("set_eolvisible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Line")>  _
        Public Property set_caret() As Global.ScintillaNET.CaretStyle
            Get
                Return CType(Me("set_caret"),Global.ScintillaNET.CaretStyle)
            End Get
            Set
                Me("set_caret") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_allowdragdrop() As Boolean
            Get
                Return CType(Me("set_allowdragdrop"),Boolean)
            End Get
            Set
                Me("set_allowdragdrop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_Overtype() As Boolean
            Get
                Return CType(Me("set_Overtype"),Boolean)
            End Get
            Set
                Me("set_Overtype") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property set_cursor() As Integer
            Get
                Return CType(Me("set_cursor"),Integer)
            End Get
            Set
                Me("set_cursor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_displaytrayicon() As Boolean
            Get
                Return CType(Me("set_displaytrayicon"),Boolean)
            End Get
            Set
                Me("set_displaytrayicon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Normal")>  _
        Public Property set_defaultwindowstate() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("set_defaultwindowstate"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("set_defaultwindowstate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_ftpusername() As String
            Get
                Return CType(Me("set_ftpusername"),String)
            End Get
            Set
                Me("set_ftpusername") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_ftpuserpass() As String
            Get
                Return CType(Me("set_ftpuserpass"),String)
            End Get
            Set
                Me("set_ftpuserpass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HOSTNAME")>  _
        Public Property set_ftphostname() As String
            Get
                Return CType(Me("set_ftphostname"),String)
            End Get
            Set
                Me("set_ftphostname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DEFAULT")>  _
        Public Property set_backupsloc() As String
            Get
                Return CType(Me("set_backupsloc"),String)
            End Get
            Set
                Me("set_backupsloc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_autobackup() As Boolean
            Get
                Return CType(Me("set_autobackup"),Boolean)
            End Get
            Set
                Me("set_autobackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property set_autobackupinterval() As Integer
            Get
                Return CType(Me("set_autobackupinterval"),Integer)
            End Get
            Set
                Me("set_autobackupinterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_alertbackup() As Boolean
            Get
                Return CType(Me("set_alertbackup"),Boolean)
            End Get
            Set
                Me("set_alertbackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_showtipsatstartup() As Boolean
            Get
                Return CType(Me("set_showtipsatstartup"),Boolean)
            End Get
            Set
                Me("set_showtipsatstartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_customcompilerloc() As String
            Get
                Return CType(Me("set_customcompilerloc"),String)
            End Get
            Set
                Me("set_customcompilerloc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_customcompilerpathvar() As String
            Get
                Return CType(Me("set_customcompilerpathvar"),String)
            End Get
            Set
                Me("set_customcompilerpathvar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_customcompilercommand() As String
            Get
                Return CType(Me("set_customcompilercommand"),String)
            End Get
            Set
                Me("set_customcompilercommand") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_customcompilerparams() As String
            Get
                Return CType(Me("set_customcompilerparams"),String)
            End Get
            Set
                Me("set_customcompilerparams") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_customcompilerrequiressecondfile() As Boolean
            Get
                Return CType(Me("set_customcompilerrequiressecondfile"),Boolean)
            End Get
            Set
                Me("set_customcompilerrequiressecondfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_customcompilerextension() As String
            Get
                Return CType(Me("set_customcompilerextension"),String)
            End Get
            Set
                Me("set_customcompilerextension") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_customcompilerenabled() As Boolean
            Get
                Return CType(Me("set_customcompilerenabled"),Boolean)
            End Get
            Set
                Me("set_customcompilerenabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_backupwhensaving() As Boolean
            Get
                Return CType(Me("set_backupwhensaving"),Boolean)
            End Get
            Set
                Me("set_backupwhensaving") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_applockpassword() As String
            Get
                Return CType(Me("set_applockpassword"),String)
            End Get
            Set
                Me("set_applockpassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_applockenabled() As Boolean
            Get
                Return CType(Me("set_applockenabled"),Boolean)
            End Get
            Set
                Me("set_applockenabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_browserusepreviewer() As Boolean
            Get
                Return CType(Me("set_browserusepreviewer"),Boolean)
            End Get
            Set
                Me("set_browserusepreviewer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_welcomeimagelocation() As String
            Get
                Return CType(Me("set_welcomeimagelocation"),String)
            End Get
            Set
                Me("set_welcomeimagelocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_displaywelcomeimage() As Boolean
            Get
                Return CType(Me("set_displaywelcomeimage"),Boolean)
            End Get
            Set
                Me("set_displaywelcomeimage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Stretch")>  _
        Public Property set_welcomeimagestyle() As String
            Get
                Return CType(Me("set_welcomeimagestyle"),String)
            End Get
            Set
                Me("set_welcomeimagestyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_openfileinselectededitor() As Boolean
            Get
                Return CType(Me("set_openfileinselectededitor"),Boolean)
            End Get
            Set
                Me("set_openfileinselectededitor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_encryptbackup() As Boolean
            Get
                Return CType(Me("set_encryptbackup"),Boolean)
            End Get
            Set
                Me("set_encryptbackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_autoencrypt() As Boolean
            Get
                Return CType(Me("set_autoencrypt"),Boolean)
            End Get
            Set
                Me("set_autoencrypt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property set_autoencryptinterval() As Integer
            Get
                Return CType(Me("set_autoencryptinterval"),Integer)
            End Get
            Set
                Me("set_autoencryptinterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_allowplugins() As Boolean
            Get
                Return CType(Me("set_allowplugins"),Boolean)
            End Get
            Set
                Me("set_allowplugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ActiveCaption")>  _
        Public Property set_toolpanelcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("set_toolpanelcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("set_toolpanelcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ActiveCaption")>  _
        Public Property set_projectexplorercolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("set_projectexplorercolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("set_projectexplorercolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ActiveCaption")>  _
        Public Property set_menustripcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("set_menustripcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("set_menustripcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_menustriptextcolorwhite() As Boolean
            Get
                Return CType(Me("set_menustriptextcolorwhite"),Boolean)
            End Get
            Set
                Me("set_menustriptextcolorwhite") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200")>  _
        Public Property set_toolpanelwidth() As Integer
            Get
                Return CType(Me("set_toolpanelwidth"),Integer)
            End Get
            Set
                Me("set_toolpanelwidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200")>  _
        Public Property set_projectexplorerwidth() As Integer
            Get
                Return CType(Me("set_projectexplorerwidth"),Integer)
            End Get
            Set
                Me("set_projectexplorerwidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_toolpanelvisibleatstartup() As Boolean
            Get
                Return CType(Me("set_toolpanelvisibleatstartup"),Boolean)
            End Get
            Set
                Me("set_toolpanelvisibleatstartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_voicepp_commandrecatstartup() As Boolean
            Get
                Return CType(Me("set_voicepp_commandrecatstartup"),Boolean)
            End Get
            Set
                Me("set_voicepp_commandrecatstartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_highlightselectedline() As Boolean
            Get
                Return CType(Me("set_highlightselectedline"),Boolean)
            End Get
            Set
                Me("set_highlightselectedline") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_usesmartindentation() As Boolean
            Get
                Return CType(Me("set_usesmartindentation"),Boolean)
            End Get
            Set
                Me("set_usesmartindentation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_usesmartcompletion() As Boolean
            Get
                Return CType(Me("set_usesmartcompletion"),Boolean)
            End Get
            Set
                Me("set_usesmartcompletion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_ftppathhistory() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_ftppathhistory"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_ftppathhistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_rsshistory() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_rsshistory"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_rsshistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_rssdefaultfeed() As String
            Get
                Return CType(Me("set_rssdefaultfeed"),String)
            End Get
            Set
                Me("set_rssdefaultfeed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property set_actionifnotabs() As Integer
            Get
                Return CType(Me("set_actionifnotabs"),Integer)
            End Get
            Set
                Me("set_actionifnotabs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_highlightmatchingbraceswhenselected() As Boolean
            Get
                Return CType(Me("set_highlightmatchingbraceswhenselected"),Boolean)
            End Get
            Set
                Me("set_highlightmatchingbraceswhenselected") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_codebookmarks() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_codebookmarks"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_codebookmarks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_showindentationguides() As Boolean
            Get
                Return CType(Me("set_showindentationguides"),Boolean)
            End Get
            Set
                Me("set_showindentationguides") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_customlang_autocompletelist() As String
            Get
                Return CType(Me("set_customlang_autocompletelist"),String)
            End Get
            Set
                Me("set_customlang_autocompletelist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_customlang_keywords0() As String
            Get
                Return CType(Me("set_customlang_keywords0"),String)
            End Get
            Set
                Me("set_customlang_keywords0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_customlang_keywords1() As String
            Get
                Return CType(Me("set_customlang_keywords1"),String)
            End Get
            Set
                Me("set_customlang_keywords1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_customlang_enabled() As Boolean
            Get
                Return CType(Me("set_customlang_enabled"),Boolean)
            End Get
            Set
                Me("set_customlang_enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_menustrip_mousehover() As Boolean
            Get
                Return CType(Me("set_menustrip_mousehover"),Boolean)
            End Get
            Set
                Me("set_menustrip_mousehover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_hoveroverinfopaneltoopen() As Boolean
            Get
                Return CType(Me("set_hoveroverinfopaneltoopen"),Boolean)
            End Get
            Set
                Me("set_hoveroverinfopaneltoopen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_speeddial_mousehover() As Boolean
            Get
                Return CType(Me("set_speeddial_mousehover"),Boolean)
            End Get
            Set
                Me("set_speeddial_mousehover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>Code Editor</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Notepad</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Code Metrics</"& _ 
            "string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Bookmarks</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Calendar</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Do"& _ 
            "cumentation</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Site Previewer</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Universal Sea"& _ 
            "rch</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Web Browser</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property set_speeddial() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_speeddial"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_speeddial") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ActiveCaption")>  _
        Public Property set_speeddial_backcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("set_speeddial_backcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("set_speeddial_backcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("InfoText")>  _
        Public Property set_terminal_backcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("set_terminal_backcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("set_terminal_backcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property set_terminal_forecolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("set_terminal_forecolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("set_terminal_forecolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 10pt")>  _
        Public Property set_terminal_font() As Global.System.Drawing.Font
            Get
                Return CType(Me("set_terminal_font"),Global.System.Drawing.Font)
            End Get
            Set
                Me("set_terminal_font") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_checkforupdates() As Boolean
            Get
                Return CType(Me("set_checkforupdates"),Boolean)
            End Get
            Set
                Me("set_checkforupdates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_confirmexit() As Boolean
            Get
                Return CType(Me("set_confirmexit"),Boolean)
            End Get
            Set
                Me("set_confirmexit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_highlightmatchingselection() As Boolean
            Get
                Return CType(Me("set_highlightmatchingselection"),Boolean)
            End Get
            Set
                Me("set_highlightmatchingselection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_notepad_linksecuritynotification() As Boolean
            Get
                Return CType(Me("set_notepad_linksecuritynotification"),Boolean)
            End Get
            Set
                Me("set_notepad_linksecuritynotification") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_recentfiles() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_recentfiles"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_recentfiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_editordocumentmap() As Boolean
            Get
                Return CType(Me("set_editordocumentmap"),Boolean)
            End Get
            Set
                Me("set_editordocumentmap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property temp_performancemode() As Boolean
            Get
                Return CType(Me("temp_performancemode"),Boolean)
            End Get
            Set
                Me("temp_performancemode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_enableperformancemodeatstartup() As Boolean
            Get
                Return CType(Me("set_enableperformancemodeatstartup"),Boolean)
            End Get
            Set
                Me("set_enableperformancemodeatstartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_apps_program() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_apps_program"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_apps_program") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_apps_arguments() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_apps_arguments"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_apps_arguments") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Each")>  _
        Public Property set_multipaste() As Global.ScintillaNET.MultiPaste
            Get
                Return CType(Me("set_multipaste"),Global.ScintillaNET.MultiPaste)
            End Get
            Set
                Me("set_multipaste") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_multiselection() As Boolean
            Get
                Return CType(Me("set_multiselection"),Boolean)
            End Get
            Set
                Me("set_multiselection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property set_wrapmode() As Global.ScintillaNET.WrapMode
            Get
                Return CType(Me("set_wrapmode"),Global.ScintillaNET.WrapMode)
            End Get
            Set
                Me("set_wrapmode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_keepfileloc() As Boolean
            Get
                Return CType(Me("set_keepfileloc"),Boolean)
            End Get
            Set
                Me("set_keepfileloc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_quickcommand_closeafterexecute() As Boolean
            Get
                Return CType(Me("set_quickcommand_closeafterexecute"),Boolean)
            End Get
            Set
                Me("set_quickcommand_closeafterexecute") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_smartpaste() As Boolean
            Get
                Return CType(Me("set_smartpaste"),Boolean)
            End Get
            Set
                Me("set_smartpaste") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_smartcopy() As Boolean
            Get
                Return CType(Me("set_smartcopy"),Boolean)
            End Get
            Set
                Me("set_smartcopy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_smartcut() As Boolean
            Get
                Return CType(Me("set_smartcut"),Boolean)
            End Get
            Set
                Me("set_smartcut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_favorites() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_favorites"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_favorites") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>Studio</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Editing</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property set_displayedtoolbars() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_displayedtoolbars"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_displayedtoolbars") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_toolbarsvisible() As Boolean
            Get
                Return CType(Me("set_toolbarsvisible"),Boolean)
            End Get
            Set
                Me("set_toolbarsvisible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ActiveCaption")>  _
        Public Property set_toolbars_backcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("set_toolbars_backcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("set_toolbars_backcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_coderecovery_enabled() As Boolean
            Get
                Return CType(Me("set_coderecovery_enabled"),Boolean)
            End Get
            Set
                Me("set_coderecovery_enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property set_coderecovery_interval() As Integer
            Get
                Return CType(Me("set_coderecovery_interval"),Integer)
            End Get
            Set
                Me("set_coderecovery_interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_highlightmatchingwords() As Boolean
            Get
                Return CType(Me("set_highlightmatchingwords"),Boolean)
            End Get
            Set
                Me("set_highlightmatchingwords") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_rememberopenedfiles() As Boolean
            Get
                Return CType(Me("set_rememberopenedfiles"),Boolean)
            End Get
            Set
                Me("set_rememberopenedfiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_openedfiles() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_openedfiles"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_openedfiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_autosave() As Boolean
            Get
                Return CType(Me("set_autosave"),Boolean)
            End Get
            Set
                Me("set_autosave") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property set_autosave_interval() As Integer
            Get
                Return CType(Me("set_autosave_interval"),Integer)
            End Get
            Set
                Me("set_autosave_interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_profilestartup() As String
            Get
                Return CType(Me("set_profilestartup"),String)
            End Get
            Set
                Me("set_profilestartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_displaysplashscreen() As Boolean
            Get
                Return CType(Me("set_displaysplashscreen"),Boolean)
            End Get
            Set
                Me("set_displaysplashscreen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Welcome")>  _
        Public Property set_startuptab() As String
            Get
                Return CType(Me("set_startuptab"),String)
            End Get
            Set
                Me("set_startuptab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_multiselectiontyping() As Boolean
            Get
                Return CType(Me("set_multiselectiontyping"),Boolean)
            End Get
            Set
                Me("set_multiselectiontyping") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_tabtriggers() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_tabtriggers"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_tabtriggers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_tabtriggers_replacephrase() As Boolean
            Get
                Return CType(Me("set_tabtriggers_replacephrase"),Boolean)
            End Get
            Set
                Me("set_tabtriggers_replacephrase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_tabtriggers_enabled() As Boolean
            Get
                Return CType(Me("set_tabtriggers_enabled"),Boolean)
            End Get
            Set
                Me("set_tabtriggers_enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_requirefilecreation() As Boolean
            Get
                Return CType(Me("set_requirefilecreation"),Boolean)
            End Get
            Set
                Me("set_requirefilecreation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_codetemplates() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_codetemplates"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_codetemplates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_highlightcurrentblock() As Boolean
            Get
                Return CType(Me("set_highlightcurrentblock"),Boolean)
            End Get
            Set
                Me("set_highlightcurrentblock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WORKSPACE")>  _
        Public Property set_quickopen_folder() As String
            Get
                Return CType(Me("set_quickopen_folder"),String)
            End Get
            Set
                Me("set_quickopen_folder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_firstlaunch() As Boolean
            Get
                Return CType(Me("set_firstlaunch"),Boolean)
            End Get
            Set
                Me("set_firstlaunch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_closebuttonactsasminimize() As String
            Get
                Return CType(Me("set_closebuttonactsasminimize"),String)
            End Get
            Set
                Me("set_closebuttonactsasminimize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_runscriptatstartup() As Boolean
            Get
                Return CType(Me("set_runscriptatstartup"),Boolean)
            End Get
            Set
                Me("set_runscriptatstartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property set_scripttorunatstartup() As String
            Get
                Return CType(Me("set_scripttorunatstartup"),String)
            End Get
            Set
                Me("set_scripttorunatstartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Top")>  _
        Public Property set_tabstriplocation() As Global.WeifenLuo.WinFormsUI.Docking.DocumentTabStripLocation
            Get
                Return CType(Me("set_tabstriplocation"),Global.WeifenLuo.WinFormsUI.Docking.DocumentTabStripLocation)
            End Get
            Set
                Me("set_tabstriplocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DEFAULT")>  _
        Public Property set_dockpanelbg() As String
            Get
                Return CType(Me("set_dockpanelbg"),String)
            End Get
            Set
                Me("set_dockpanelbg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_recentlyclosedfiles() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_recentlyclosedfiles"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_recentlyclosedfiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_filehistory() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_filehistory"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_filehistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_displaystudiobgimage() As Boolean
            Get
                Return CType(Me("set_displaystudiobgimage"),Boolean)
            End Get
            Set
                Me("set_displaystudiobgimage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_recordclipboardhistory() As Boolean
            Get
                Return CType(Me("set_recordclipboardhistory"),Boolean)
            End Get
            Set
                Me("set_recordclipboardhistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_clipboardhistory() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_clipboardhistory"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_clipboardhistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_rememberclipboardhistory() As Boolean
            Get
                Return CType(Me("set_rememberclipboardhistory"),Boolean)
            End Get
            Set
                Me("set_rememberclipboardhistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property set_homekeywrappedlines() As Boolean
            Get
                Return CType(Me("set_homekeywrappedlines"),Boolean)
            End Get
            Set
                Me("set_homekeywrappedlines") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property set_storenotifications() As Boolean
            Get
                Return CType(Me("set_storenotifications"),Boolean)
            End Get
            Set
                Me("set_storenotifications") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
        Public Property set_notifications() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("set_notifications"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("set_notifications") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.XDev_Studio.My.MySettings
            Get
                Return Global.XDev_Studio.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
