Friend Class ConverterVariables

    Public DataItem As String
    Public DataNumber As Long
    Public BinNumber As String
    Public DataTypeString As String
    Public HexToDecSolution As String
    Public HexToBinSolution As String
    Public DecToHexSolution As String
    Public BinToHexSolution As String
    Public BinToDecSolution As String
    Public BCDToBinSolution As String
    Public DataBit(15) As Integer
    Public HexBit(7) As String
    Public BinString(3) As String
    Public DecHexDigit As Integer
    Public ConversionItem As String
    Public ConversionNumber As Integer
    Public CommunityCounter As Integer
    Public CommunityResult As Integer
    Public CommunityItem As String
    Public ASCIINumber As String
    Public ASCIIToHexSolution As String
    Public ASCIIToBinSolution As String
    Public ConversionSolution1 As Double
    Public ConversionSolution2 As Double
    Public FirstConversionItemSet As Boolean
    Public SecondConversionItemSet As Boolean
    Public TimeRemainder As Integer
    Public AMPM1 As Integer
    Public Day1 As Integer
    Public Hour1 As Integer
    Public Minute1 As Integer
    Public Second1 As Integer
    Public AMPM2 As Integer
    Public Day2 As Integer
    Public Hour2 As Integer
    Public Minute2 As Integer
    Public Second2 As Integer
    Public DayElapsed As Integer
    Public HourElapsed As Integer
    Public MinuteElapsed As Integer
    Public SecondElapsed As Integer
    Public ConversionRoundSetting As Integer
    Public AngleRoundSetting As Integer
    Public SideRoundSetting As Integer
    Public CourtesanRoundSetting As Integer
    Public TimeRoundSetting As Integer
    Public CalcRoundSetting As Integer
    Public CourtesanSolution1 As Double
    Public CourtesanSolution2 As Double
    Public CourtesanSolution3 As Double
    Public CourtesanSolution4 As Double
    Public Solution1X As String
    Public Solution1Y As String
    Public Solution2X As String
    Public Solution2Y As String
    Public CalcItem1 As String
    Public CalcItem2 As String
    Public CalcTemp As String
    Public CalcNumber1 As Double
    Public CalcNumber2 As Double
    Public CalcSolution As Double
    Public CalcFlag As Boolean
    Public DescString1 As String
    Public DescString2 As String
    Public DescString3 As String
    Public DescString4 As String
    Public DescString5 As String
    Public DescString6 As String
    Public SolutionSelector As Integer
    Public CaseSelector As Integer
    Public SolutionSendCapable As Boolean
    Public SolutionGetCapable As Boolean

End Class
